language: node_js
node_js:
- '0.10'
install:
- npm install -g grunt-cli bower
- npm install
- bower install
script:
- npm test
notifications:
  email:
  - rashid.khan@elasticsearch.com
  - spencer.alger@elasticsearch.com
  hipchat:
    rooms:
      secure: AFhp0iboaeshokQnzRvoKPElb/JOvZ09X9mi58KbxI4iYlQ1nysvudV1b7YG8wxV9av3twgvfbcgzAoHyKhC2MZJDLzDHnZFn8r2OQXzjYpFxJuhAVirO4Weo0wi2Z78/OkxQo87gWYFa24qc8urR/Dfor4WdoWfCsJU8tQ7t5I=
    format: html
    on_success: change
    template:
    - ! '%{repository_slug}/%{branch} by %{author}: %{commit_message} (<a href="%{build_url}">open</a>)'